social-before/config/routes.rb
Social::Application.routes.draw do
  root to: 'users#index'
  resources :users
  resources :projects
end

social-before/app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
end

social-before/app/models/user.rb
class User < ActiveRecord::Base
  has_many :projects
end

social-before/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

social-before/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def new
    @project = Project.new
  end

  def create
    @project = Project.new(params[:project])
    @project.user = User.first # you would normally add it to the current user
    if @project.save
      redirect_to @project.user, notice: "Project has been created"
    else
      render "new"
    end
  end
end

social-before/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to @user, notice: "Profile has been updated."
    else
      render "edit"
    end
  end
end

social-before/app/helpers/application_helper.rb
module ApplicationHelper
end

social-before/app/helpers/projects_helper.rb
module ProjectsHelper
end

social-before/app/helpers/users_helper.rb
module UsersHelper
end

social-before/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sign Up</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, id: "flash_#{name}" %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

social-before/app/views/projects/new.html.erb
<h1>New Project</h1>

<%= form_for @project do |f| %>
  <% if @project.errors.any? %>
    <ul class="errors">
    <% @project.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

social-before/app/views/users/edit.html.erb
<h1>Edit Profile</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <ul class="errors">
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

social-before/app/views/users/index.html.erb
<h1>Users</h1>

<ul>
<% @users.each do |user| %>
  <li><%= link_to user.name, user %></li>
<% end %>
</ul>

social-before/app/views/users/show.html.erb
<h1>User Profile</h1>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>
<p>
  <b>Admin:</b>
  <%= @user.admin? ? "Yes" : "No" %>
</p>

<p><%= link_to "Edit Profile", edit_user_path(@user) %></p>

<h3><%= pluralize @user.projects.size, "Project" %></h3>

<ul>
<% @user.projects.each do |project| %>
  <li><%= project.name %></li>
<% end %>
</ul>

<%= link_to "New Project", new_project_path %>